language: python
cache: pip
python:
    - "2.7"
install:
    - pip install numpy astropy healpy ephem matplotlib
    - python setup.py develop
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script:
    tests/test_rm.py
